### ISSUE TITLE
Core saves files in the incorrect directory (OSX)

### ISSUE THREAD

**Issue by zach-morris** [kodi-game/game.libretro.vice#2]
Version tested: RetroPlayer 18 alpha1 2018-02-11

Issue: Vice core saved files in the same directory that the Kodi app is in (Applications).

The files the core created in this directory are:
vicelog.txt
vicerc0
FA7775AE.eeprom
cdrom.eeprom

I would expect these files to be saved in userdata

**Comment by garbear** [comment]
Should this be closed alongside https://github.com/garbear/xbmc/issues/93?

**Comment by zach-morris** [comment]
I just tried it, Vice still creates vicerc0 in the application directory, just by starting the vice core addon.  Contents of the file:
```
[C64]
SDLStatusbar=1
SoundDeviceName="retro"
SoundBufferSize=100
VirtualDevices=1
IECReset=1
CIA1Model=0
CIA2Model=0
VICIIVideoCache=1
VICIIHwScale=0
SidEngine=0
SidModel=0
RetroJoy=1
DriveTrueEmulation=0
Drive8Type=1541
```

**Comment by garbear** [comment]
I confirmed that Vice is hard-coded to use the current working directory (the application directory in this case). I've opened an issue upstream: https://github.com/libretro/vice-libretro/issues/53

**Comment by garbear** [comment]
It looks like this was fixed two days ago: https://github.com/libretro/vice-libretro/pull/72. Can't say when, but eventually I'll run kodi-game-scripting across all the cores and update to the latest versions.

**Comment by garbear** [comment]
I updated all our cores. Can you try with a recent vice?

**Comment by zach-morris** [comment]
works now, thanks!

**Comment by garbear** [comment]
Speaking of filesystem work, when game.libretro gets the C++ interface update, the libretro VFS API can be supported. I finished support for the libretro VFS API v1 here: https://github.com/kodi-game/game.libretro/commit/vfs (though libretro vfs API is currently on v3). 

Do you know of any cores that use the VFS API I can test with?

**Comment by zach-morris** [comment]
[Gen Plus GX](https://github.com/libretro/Genesis-Plus-GX/pull/124) uses vfs to some degree i know
